<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.0.22</Version>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WoowzLib.Physic3D\WoowzLib.Physic3D.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BepuPhysics" Version="2.4.0" />
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
        <Exec Command="&quot;$(ProjectDir)..\..\CSVersionUpdater\CSVersionUpdater\bin\Debug\net8.0\CSVersionUpdater.exe&quot; &quot;$(MSBuildProjectFullPath)&quot;" />
    </Target>

</Project>