<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>

        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\WoowzLib\WoowzLib.Core\WoowzLib.Core.csproj" />
        <ProjectReference Include="..\..\WoowzLib\WoowzLib.Logger\WoowzLib.Logger.csproj" />
    </ItemGroup>
    
</Project>